// The MIT License (MIT)

// Copyright 2015 Siney/Pangweiwei siney@yeah.net
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

namespace SLua
{
    using System.Collections.Generic;
    using System;

    public class CustomExport
    {
        public static void OnGetAssemblyToGenerateExtensionMethod(out List<string> list)
        {
            list = new List<string> {
                "PluginFramework",
                "DOTween",
                "UnityEngine",
                "UnityEngine.CoreModule",
                "UnityEngine.UIModule",
                "UnityEngine.TextRenderingModule",
                "UnityEngine.AnimationModule",
                "UnityEngine.PhysicsModule",
                "UnityEngine.ParticleSystemModule",
                "UnityEngine.ImageConversionModule",
                "UnityEngine.VideoModule",
                "UnityEngine.UI",
            };
        }

        public static void OnAddCustomClass(LuaCodeGen.ExportGenericDelegate add)
        {
            add(typeof(System.Func<int>), null);
            add(typeof(System.Action<int, string>), null);
            add(typeof(System.Action<int, Dictionary<int, object>>), null);
            add(typeof(System.Exception), "System.Exception");
            add(typeof(string), "System.String");
            add(typeof(System.Object), "System.Object");
            add(typeof(System.Array), "System.Array");
            add(typeof(System.Collections.ArrayList), "System.Collections.ArrayList");
            add(typeof(System.Collections.Hashtable), "System.Collections.Hashtable");
            add(typeof(System.Collections.BitArray), "System.Collections.BitArray");
            add(typeof(System.Collections.Queue), "System.Collections.Queue");
            add(typeof(System.Collections.Stack), "System.Collections.Stack");
            add(typeof(System.Collections.SortedList), "System.Collections.SortedList");
            add(typeof(byte[]), "ByteArray");
            add(typeof(System.Boolean), "System.Boolean");
            add(typeof(System.SByte), "System.SByte");
            add(typeof(System.Byte), "System.Byte");
            add(typeof(System.Int16), "System.Int16");
            add(typeof(System.UInt16), "System.UInt16");
            add(typeof(System.Int32), "System.Int32");
            add(typeof(System.UInt32), "System.UInt32");
            add(typeof(System.Int64), "System.Int64");
            add(typeof(System.UInt64), "System.UInt64");
            add(typeof(System.Single), "System.Single");
            add(typeof(System.Double), "System.Double");
            add(typeof(System.Convert), "System.Convert");
            add(typeof(System.TypeCode), "System.TypeCode");
            add(typeof(System.Type), "System.Type");
            add(typeof(System.IO.File), "System.IO.File");
            add(typeof(System.IO.Path), "System.IO.Path");
            add(typeof(System.IO.Directory), "System.IO.Directory");
            add(typeof(System.IO.DirectoryInfo), "System.IO.DirectoryInfo");
            add(typeof(System.IO.Stream), "System.IO.Stream");
            add(typeof(System.IO.FileStream), "System.IO.FileStream");
            add(typeof(System.IO.BinaryReader), "System.IO.BinaryReader");
            add(typeof(System.IO.BinaryWriter), "System.IO.BinaryWriter");
            add(typeof(System.TimeSpan), "System.TimeSpan");
            add(typeof(System.TimeZone), "System.TimeZone");
            add(typeof(System.Math), "System.Math");
            add(typeof(System.Random), "System.Random");
            add(typeof(System.Delegate), "System.Delegate");
            add(typeof(System.Text.StringBuilder), "System.Text.StringBuilder");
            add(typeof(System.Text.Encoding), "System.Text.Encoding");
            add(typeof(System.Text.ASCIIEncoding), "System.Text.ASCIIEncoding");
            add(typeof(System.Text.UTF8Encoding), "System.Text.UTF8Encoding");
            add(typeof(System.Text.UnicodeEncoding), "System.Text.UnicodeEncoding");
            add(typeof(System.Text.RegularExpressions.Regex), "System.Text.RegularExpressions.Regex");
            add(typeof(System.Text.RegularExpressions.Match), "System.Text.RegularExpressions.Match");
            add(typeof(System.Text.RegularExpressions.MatchCollection), "System.Text.RegularExpressions.MatchCollection");
            add(typeof(System.Text.RegularExpressions.Group), "System.Text.RegularExpressions.Group");
            add(typeof(System.Text.RegularExpressions.GroupCollection), "System.Text.RegularExpressions.GroupCollection");
            add(typeof(System.Text.RegularExpressions.Capture), "System.Text.RegularExpressions.Capture");
            add(typeof(System.Text.RegularExpressions.CaptureCollection), "System.Text.RegularExpressions.CaptureCollection");
            add(typeof(System.GC), "System.GC");
            add(typeof(LinkedListNode<CsLibrary.EntityInfo>), "LinkedListNodeEntityInfo");
            add(typeof(KeyValuePair<int, int>), "IntIntPair");
            add(typeof(KeyValuePair<int, float>), "IntFloatPair");
            add(typeof(KeyValuePair<int, string>), "IntStrPair");
            add(typeof(KeyValuePair<int, object>), "IntObjPair");
            add(typeof(KeyValuePair<int, UnityEngine.Object>), "IntUobjPair");
            add(typeof(KeyValuePair<string, int>), "StrIntPair");
            add(typeof(KeyValuePair<string, float>), "StrFloatPair");
            add(typeof(KeyValuePair<string, string>), "StrStrPair");
            add(typeof(KeyValuePair<string, object>), "StrObjPair");
            add(typeof(KeyValuePair<string, UnityEngine.Object>), "StrUobjPair");
            // add your custom class here
            // add( type, typename)
            // type is what you want to export
            // typename used for simplify generic type name or rename, like List<int> named to "ListInt", if not a generic type keep typename as null or rename as new type name
        }

        public static HashSet<string> OnAddCustomNamespace()
        {
            return new HashSet<string> {
                //"NLuaTest.Mock"
            };
        }

        public static void OnAddCustomAssembly(ref List<string> list)
        {
            // add your custom assembly here
            // you can build a dll for 3rd library like ngui titled assembly name "NGUI", put it in Assets folder
            // add its name into list, slua will generate all exported interface automatically for you

            //list.Add("NGUI");
            list.Add("protobuf-net");
            list.Add("LitJson");
            list.Add("PluginFramework");
            list.Add("Common");
            list.Add("Dsl");
            list.Add("StorySystem");
            list.Add("FairyGUI");
            list.Add("ClientConfig");
            list.Add("DOTween");
        }

        public static void OnGetCustomAssemblyUseList(out HashSet<string> list)
        {
            list = new HashSet<string> {
            };
        }
        public static void OnGetCustomAssemblyNoUseList(out List<string> list)
        {
            list = new List<string> {
            };
        }

        public static List<string> FunctionFilterList = new List<string>()
        {
            "System.Single.IsFinite",
            "System.Double.IsFinite",
            "System.Text.StringBuilder.AppendFormat",
            "System.Type.IsSZArray",
            "System.IO.Stream.CopyToAsync",
            "System.IO.Stream.FlushAsync",
            "System.IO.Stream.ReadAsync",
            "System.IO.Stream.BeginRead",
            "System.IO.Stream.EndRead",
            "System.IO.Stream.WriteAsync",
            "System.IO.Stream.BeginWrite",
            "System.IO.Stream.EndWrite",
            "UnityEngine.Debug.LogFormat",
            "UnityEngine.Debug.LogWarningFormat",
            "UnityEngine.Debug.LogErrorFormat",
            "UnityEngine.Debug.LogAssertionFormat",
            "UnityEngine.WWW.GetMovieTexture",
            "UnityEngine.Font.GetPathsToOSFonts",
        };
        // white list
        public static void OnGetUseList(out HashSet<string> list)
        {
            list = new HashSet<string>
            {
"_PhaseList",
"AiQueryComparer",
"AnimatorWrapperState",
"BoolList",
"BoxedValue",
"BoxedValueList",
"ByteList",
"ClientProfiler",
"ConfigManagerBase",
"Cs2LuaLib",
"CSharp2LuaAdaptor",
"CsLibrary.AccountSystem",
"CsLibrary.AiStateInfo",
"CsLibrary.AnimatorController",
"CsLibrary.AnimatorController+IdleMode",
"CsLibrary.AudioManager",
"CsLibrary.AudioManager+AudioPlayFlag",
"CsLibrary.AudioManager+VoiceType",
"CsLibrary.AvatarDecalIndex",
"CsLibrary.AvatarInformation",
"CsLibrary.AvatarReferOtherParams",
"CsLibrary.AvatarSystem",
"CsLibrary.BattleManualController",
"CsLibrary.BattleState",
"CsLibrary.BattleState+eStatus",
"CsLibrary.BeforehandMoveImpact",
"CsLibrary.BlackBoard",
"CsLibrary.BoneGroup",
"CsLibrary.BoneJceInfo",
"CsLibrary.BoneModifyValue",
"CsLibrary.BoneTransform",
"CsLibrary.BuffInfo",
"CsLibrary.BuffStateInfo",
"CsLibrary.BulletBehavious",
"CsLibrary.Calculator",
"CsLibrary.CanDo",
"CsLibrary.CanDo+CastResult",
"CsLibrary.CharacterConfigInterface",
"CsLibrary.CharacterProperty",
"CsLibrary.CharacterPropertyEnum",
"CsLibrary.CheckPointContext",
"CsLibrary.ClientModelPolicy",
"CsLibrary.ClientModule",
"CsLibrary.ClientModule+ShuiLongCheSkillData",
"CsLibrary.CmdInterface",
"CsLibrary.CollectInfo",
"CsLibrary.ConfigManagerSerializer",
"CsLibrary.ConnectionType",
"CsLibrary.Converter",
"CsLibrary.CustomExportImageConversion",
"CsLibrary.DamageImpact",
"CsLibrary.DebugTime",
"CsLibrary.DecalInfo",
"CsLibrary.DecalJceInfo",
"CsLibrary.DecalSprite",
"CsLibrary.DynamicBlockManager",
"CsLibrary.EffectManager",
"CsLibrary.EffectManager+ParticalInfo",
"CsLibrary.EnmityInfo",
"CsLibrary.EntityCategoryEnum",
"CsLibrary.EntityInfo",
"CsLibrary.EntityInfo+eCompanioType",
"CsLibrary.EntityInfo+eMirrorType",
"CsLibrary.EntityInfo+eVehicleLinkType",
"CsLibrary.EntityInfoDictionary",
"CsLibrary.EntityInfoList",
"CsLibrary.EntityTransform",
"CsLibrary.EntityViewAvatarConfig",
"CsLibrary.EntityViewModel",
"CsLibrary.EventRegister",
"CsLibrary.ExcuteAnimatorDelayShowCmd",
"CsLibrary.ExcuteAnimatorParamCmd",
"CsLibrary.ExcuteAnimatorPlayAnimCmd",
"CsLibrary.ExcuteNoParaFuncCmd",
"CsLibrary.ExecuteServerGm",
"CsLibrary.FaceJaceInfo",
"CsLibrary.FaceJceTools",
"CsLibrary.FaceSavedData",
"CsLibrary.FakeResUpPartProgress",
"CsLibrary.FGUIResourceSystem",
"CsLibrary.FormalVersion",
"CsLibrary.FunLoadLevelComplete",
"CsLibrary.GameEventLib",
"CsLibrary.Geometry",
"CsLibrary.GlobalVariables",
"CsLibrary.GmCommands.ClientGmStorySystem",
"CsLibrary.GmCommands.DebugCommand",
"CsLibrary.GmCommands.GlobalDebugValues",
"CsLibrary.GmCommands.IntDebugValue",
"CsLibrary.GUIResourceSystem",
"CsLibrary.GVoiceSystem",
"CsLibrary.HairData",
"CsLibrary.HairJceInfo",
"CsLibrary.Helper",
"CsLibrary.Helper+Random",
"CsLibrary.HomePath",
"CsLibrary.HtmlPageContext",
"CsLibrary.IAccount",
"CsLibrary.IAccountInfo",
"CsLibrary.IAnimatorStateHolder",
"CsLibrary.IAudioWrapper",
"CsLibrary.IgnoreImpact",
"CsLibrary.IGVoice",
"CsLibrary.IHeightMapProxy",
"CsLibrary.ILogicModuleProxy",
"CsLibrary.IMusicData",
"CsLibrary.Int2RandomAction",
"CsLibrary.IntFashionConfigDict",
"CsLibrary.IntFashionConfigDictList",
"CsLibrary.IntProtoFieldDict",
"CsLibrary.IntProtoFieldDictList",
"CsLibrary.IQSConnection",
"CsLibrary.IRopeManager",
"CsLibrary.IScriptProxy",
"CsLibrary.ISoundPlayer",
"CsLibrary.IYueShiConcertData",
"CsLibrary.IYueShiMusicData",
"CsLibrary.KdObjectTree",
"CsLibrary.KdObjectTree+IVisitor",
"CsLibrary.KdTreeObject",
"CsLibrary.LogicModuleProxy",
"CsLibrary.LoginAndUpdateCsLib",
"CsLibrary.LoginAndUpdateCsLib+ShowConfirmDialogCallback",
"CsLibrary.LoginAndUpdateUserInfo",
"CsLibrary.LogNetworkWrap",
"CsLibrary.LogSystem",
"CsLibrary.LookIKInterface",
"CsLibrary.MakeupData",
"CsLibrary.MessageIntercepter",
"CsLibrary.MessagePacker",
"CsLibrary.MovementDebugger",
"CsLibrary.MovementInfo",
"CsLibrary.MovementInfo+FallData",
"CsLibrary.MovementInfo+FallData+FallType",
"CsLibrary.MovementInfo+PathInfo",
"CsLibrary.MovementSystem",
"CsLibrary.MovementUtility",
"CsLibrary.MovementUtility+WaterType",
"CsLibrary.MultiBodyController",
"CsLibrary.MultiBodyController+MountDataModel",
"CsLibrary.MusicPlayer",
"CsLibrary.MyAction",
"CsLibrary.NativeUtilSystem",
"CsLibrary.NetworkMessagePools",
"CsLibrary.NetworkSystem",
"CsLibrary.NpcCollisionManager",
"CsLibrary.NpcTypeEnum",
"CsLibrary.ObjectNewDelegation",
"CsLibrary.ObjectNewRequest",
"CsLibrary.OnBattleAnimEvent",
"CsLibrary.OnConnectDelegation",
"CsLibrary.OnDisconnectDelegation",
"CsLibrary.OnDownloadRecordFileCompleteDelegation",
"CsLibrary.OnErrorDelegation",
"CsLibrary.OnJoinRoomCompleteDelegation",
"CsLibrary.OnMidasPayDelegation",
"CsLibrary.OnPlayRecordFilCompleteDelegation",
"CsLibrary.OnQuitRoomCompleteDelegation",
"CsLibrary.OnReceiveDataDelegation",
"CsLibrary.OnReconnectDelegation",
"CsLibrary.OnStreamSpeechToTextDelegation",
"CsLibrary.OnUploadReccordFileCompleteDelegation",
"CsLibrary.PartTexture",
"CsLibrary.PathInfoPoint",
"CsLibrary.PathInfoPointList",
"CsLibrary.PathMoveResult",
"CsLibrary.PlayRandomIdle",
"CsLibrary.Plugin.IPluginProxy",
"CsLibrary.Plugin.PluginProxy",
"CsLibrary.ProjectionEffect",
"CsLibrary.ProjectionEffectGenerator",
"CsLibrary.PropertyConstriction",
"CsLibrary.ProtoBufferField",
"CsLibrary.ProtoBufferMessage",
"CsLibrary.PublishSubscribeSystemBase",
"CsLibrary.QSEvent",
"CsLibrary.QSLogger",
"CsLibrary.RandomAction",
"CsLibrary.RandomStrategyAbstract",
"CsLibrary.ReconnType",
"CsLibrary.ResourceLoader",
"CsLibrary.ResourceLoadQueueEnum",
"CsLibrary.ResourceSystem",
"CsLibrary.ResourceType",
"CsLibrary.RobotTest",
"CsLibrary.SceneBlockLoad",
"CsLibrary.SceneMusicData",
"CsLibrary.SettingVariables",
"CsLibrary.Skill.Trigers.TriggerUtil",
"CsLibrary.SkillDebugger",
"CsLibrary.SkillDebugger+Circle",
"CsLibrary.SkillDebugger+RangeBase",
"CsLibrary.SkillDebugger+Rect",
"CsLibrary.SkillDebugger+Ring",
"CsLibrary.SkillDebugger+Sector",
"CsLibrary.SkillDisplaySetting",
"CsLibrary.SkillImpactChain",
"CsLibrary.SkillInfoDynamic",
"CsLibrary.SkillInfoDynamicManager",
"CsLibrary.SRT",
"CsLibrary.Story.GfxStorySystem",
"CsLibrary.StrBoneTransformDict",
"CsLibrary.TimeUtility",
"CsLibrary.TrackEvent",
"CsLibrary.TypedEntityEnum",
"CsLibrary.UnityGeometry",
"CsLibrary.VehicleFinishDelegation",
"CsLibrary.VoxelManager",
"CsLibrary.VoxelManager+MoveResult",
"CsLibrary.WeaponMask",
"CsLibrary.WeatherManager",
"CsLibrary.WeatherServerControl",
"DG.Tweening.DOTween",
"DG.Tweening.DOVirtual",
"DG.Tweening.ShortcutExtensions",
"DG.Tweening.Tween",
"DG.Tweening.TweenCallback",
"DG.Tweening.Tweener",
"DG.Tweening.TweenExtensions",
"DG.Tweening.TweenSettingsExtensions",
"Dict",
"DisplayerConfigInDll.ConfigBase",
"DisplayerConfigInDll.ShowProgressConfig",
"DisplayerConfigInDll.ShowSkillRangeConfig",
"Dsl.FunctionData",
"Dsl.ISyntaxComponent",
"Dsl.StatementData",
"EntityDisplayer",
"EntityDisplayer+DisplayerView",
"EntityDisplayer+LookAtInfo",
"EntityDisplayer+ShowEnum",
"EntityDisplayerList",
"EntitySkillContext",
"FairyGUI.BlendMode",
"FairyGUI.BlurFilter",
"FairyGUI.Container",
"FairyGUI.Controller",
"FairyGUI.DisplayObject",
"FairyGUI.DisplayOptions",
"FairyGUI.DissolveFilter",
"FairyGUI.DragDropManager",
"FairyGUI.EaseType",
"FairyGUI.EventCallback0",
"FairyGUI.EventCallback1",
"FairyGUI.EventContext",
"FairyGUI.EventDispatcher",
"FairyGUI.EventListener",
"FairyGUI.GButton",
"FairyGUI.GComboBox",
"FairyGUI.GComponent",
"FairyGUI.GearBase",
"FairyGUI.GGraph",
"FairyGUI.GGroup",
"FairyGUI.GImage",
"FairyGUI.GList",
"FairyGUI.GLoader",
"FairyGUI.GMovieClip",
"FairyGUI.GObject",
"FairyGUI.GoWrapper",
"FairyGUI.GProgressBar",
"FairyGUI.GRichTextField",
"FairyGUI.GRoot",
"FairyGUI.GSlider",
"FairyGUI.GTextField",
"FairyGUI.GTextInput",
"FairyGUI.GTween",
"FairyGUI.GTweenCallback",
"FairyGUI.GTweener",
"FairyGUI.HitTestMode",
"FairyGUI.IKeyboard",
"FairyGUI.Image",
"FairyGUI.InputEvent",
"FairyGUI.InputTextField",
"FairyGUI.ListItemRenderer",
"FairyGUI.LongPressGesture",
"FairyGUI.MovieClip",
"FairyGUI.NGraphics",
"FairyGUI.NTexture",
"FairyGUI.PackageItem",
"FairyGUI.PinchGesture",
"FairyGUI.PlayCompleteCallback",
"FairyGUI.Relations",
"FairyGUI.RelationType",
"FairyGUI.RichTextField",
"FairyGUI.RotationGesture",
"FairyGUI.ScrollPane",
"FairyGUI.ShaderConfig",
"FairyGUI.Stage",
"FairyGUI.Stage+OnClickCommonHandler",
"FairyGUI.SwipeGesture",
"FairyGUI.TextField",
"FairyGUI.TextFormat",
"FairyGUI.TimerCallback",
"FairyGUI.Timers",
"FairyGUI.TouchScreenKeyboard",
"FairyGUI.Transition",
"FairyGUI.TransitionHook",
"FairyGUI.TreeNode",
"FairyGUI.TreeView",
"FairyGUI.TreeView+TreeNodeRenderDelegate",
"FairyGUI.UIConfig",
"FairyGUI.UIContentScaler",
"FairyGUI.UIContentScaler+ScreenMatchMode",
"FairyGUI.UIPackage",
"FairyGUI.UIPanel",
"FairyGUI.Utils.HtmlElement",
"FairyGUI.Utils.HtmlParseOptions",
"FguiTimerWrap",
"FloatList",
"FloatStoryValue",
"GameObjectList",
"GGraphListForCs2lua",
"GLoaderListForCs2lua",
"GProgressBarListForCs2lua",
"GRichTextFieldListForCs2lua",
"GTextFieldListForCs2lua",
"GuidanceNearstNpcQueryCallbackHelper",
"IAudioLoadManager",
"Idle",
"Impact",
"ImpactListForCs2lua",
"Integer64",
"Integer64Msg",
"Integer64MsgList",
"IntFloatDict",
"IntHashSet",
"IntIntDict",
"IntList",
"IntObjSortedDict",
"IntStoryValue",
"IntStrDict",
"JoystickMove",
"LitJson.JsonData",
"LitJson.JsonMapper",
"MakeupRTPoolManager",
"MessageDefine.ENUM_MOVE_MODE",
"MessageDefine.eQS_ATTACK_TYPE",
"MessageDefine.eQS_AVATAR_TYPE",
"MessageDefine.eSITDOWN_TYPE",
"MessageDefine.eTYPE_COMBINE_NPC_EVENT",
"MessageDefine.FLASH_MOVE_TYPE",
"MessageDefine.IJceMessage",
"MessageDefine.LOADING_TYPE",
"MessageDefine.MessageEnum2Object",
"MessageDefine.MoveCastPoint",
"MessageDefine.MoveType_t",
"MessageDefine.MSG_TRoleInfoList",
"MessageDefine.QSCMD_CHIEF_UPLOAD_LOGSC",
"MessageDefine.QSCMD_CLIENT_NOTIFYCS",
"MessageDefine.QSCMD_MIRROR_FOLLOW_LEAVE_POSSC",
"MessageDefine.QSCMD_MSDK_LOGINCS",
"MessageDefine.QSCMD_MSDK_LOGINSC",
"MessageDefine.QSCMD_NETWORKDETECTIONCS",
"MessageDefine.QSCMD_PAINT_SQUARESC",
"MessageDefine.SkillTarget",
"MessageDefine.SkillTargetInfo",
"MessageDefine.SnsFriendInfo",
"MessageDefine.TRoleInfo",
"MessageDefine.TRoleInfoList",
"MessageDefine.TZoneInfo",
"MessageDefine.TZoneRoleListSelf",
"MessageDefine.WORLD_DIR",
"MessageDefine.WORLD_POS",
"MessageUtility",
"MonoBehaviourProxy",
"MountIdle",
"MoveBase",
"MovementController",
"MoveTypeMask",
"ObjIntDict",
"ObjList",
"PathMove",
"PlayerOptInfo",
"PluginFramework.EffectUtils",
"PluginFramework.EffectUtils+LodOffset",
"PluginFramework.LookAtImpact",
"PluginFramework.MoveImpact",
"PluginFramework.Skill.BodyObstacle",
"PluginFramework.Skill.FriendSel",
"PluginFramework.Skill.ImpactFactory",
"PluginFramework.Skill.JoyStickAO",
"PluginFramework.Skill.SkillUtils",
"PluginFramework.Skill.SkillUtils+CalcTargetsResult",
"PluginFramework.Skill.SkillUtils+FindImpactFuncDelegation",
"PluginFramework.Skill.SkillUtils+TargetIdWithInfo",
"PluginFramework.Skill.TargetLock",
"PluginFramework.Skill.TargetLock+E_LockType",
"PluginFramework.SkillCaster",
"PluginFramework.SkillCaster+ECastFrom",
"PluginFramework.SkillCaster+RemoveDisplayerFilter",
"PluginFramework.SkillCaster+RemoveImpactFilter",
"PluginFramework.SkillInstanceBase",
"PluginFramework.SkillInstanceRemote",
"PluginFramework.SkillPhase",
"PluginFramework.SkillPhaseList",
"ProtoString",
"RenderImage",
"RenderImage+AdaptMode",
"RT_SizeType",
"RVO.RVOManager",
"SbyteList",
"ScriptTimeProfiler",
"ScriptTimeProfiler+SampleEnum",
"ShortList",
"SimpleJsonGCloud.JSON",
"SimpleJsonGCloud.JSONNode",
"SkillDisplayer.Displayer",
"StoryPathJump",
"StorySystem.IStoryValue",
"StorySystem.StoryInstance",
"StorySystem.StoryMessageHandler",
"StorySystem.StoryValue",
"StorySystem.StoryValueParams",
"StorySystem.StoryValueResult",
"StrFloatDict",
"StringConcatUtil",
"StrIntDict",
"StrList",
"StrListList",
"StrStack",
"StrStoryValue",
"StrStrDict",
"System.Action",
"System.Array",
"System.BitConverter",
"System.Boolean",
"System.Byte",
"System.Char",
"System.Collections.ArrayList",
"System.Collections.BitArray",
"System.Collections.IComparer",
"System.Collections.IEnumerable",
"System.Collections.IEnumerator",
"System.Convert",
"System.DateTime",
"System.DateTimeOffset",
"System.Delegate",
"System.Diagnostics.StackTrace",
"System.Double",
"System.Enum",
"System.Environment",
"System.Exception",
"System.GC",
"System.Globalization.CultureInfo",
"System.IFormatProvider",
"System.Int16",
"System.Int32",
"System.Int64",
"System.IO.BinaryReader",
"System.IO.BinaryWriter",
"System.IO.Directory",
"System.IO.DirectoryInfo",
"System.IO.File",
"System.IO.FileAccess",
"System.IO.FileInfo",
"System.IO.FileMode",
"System.IO.FileStream",
"System.IO.FileSystemInfo",
"System.IO.Path",
"System.IO.SeekOrigin",
"System.IO.Stream",
"System.Linq.Enumerable",
"System.Math",
"System.Net.IPAddress",
"System.Net.NetworkInformation.IPAddressInformation",
"System.Net.NetworkInformation.IPInterfaceProperties",
"System.Net.NetworkInformation.NetworkInterface",
"System.NotImplementedException",
"System.Object",
"System.Random",
"System.Reflection.Assembly",
"System.Reflection.BindingFlags",
"System.Reflection.FieldInfo",
"System.Reflection.MemberInfo",
"System.Reflection.PropertyInfo",
"System.SByte",
"System.Security.Cryptography.HashAlgorithm",
"System.Security.Cryptography.MD5CryptoServiceProvider",
"System.Single",
"System.String",
"System.StringComparison",
"System.StringSplitOptions",
"System.Text.Encoding",
"System.Text.RegularExpressions.Capture",
"System.Text.RegularExpressions.Group",
"System.Text.RegularExpressions.GroupCollection",
"System.Text.RegularExpressions.Match",
"System.Text.RegularExpressions.MatchCollection",
"System.Text.RegularExpressions.Regex",
"System.Text.RegularExpressions.RegexOptions",
"System.Text.StringBuilder",
"System.TimeSpan",
"System.TimeZone",
"System.Type",
"System.UInt16",
"System.UInt32",
"System.UInt64",
"TableConfig.AbnormalConfig",
"TableConfig.ActorConfig",
"TableConfig.Buff",
"TableConfig.CampRelation",
"TableConfig.FashionConfig",
"TableConfig.ImpactConfig",
"TableConfig.MountInfo",
"TableConfig.NpcInfo",
"TableConfig.NpcRepresent",
"TableConfig.NumberConstant",
"TableConfig.PerformanceSettings",
"TableConfig.PetInfo",
"TableConfig.Phase",
"TableConfig.SceneInfo",
"TableConfig.SkillChain",
"TableConfig.SkillCombo",
"TableConfig.SkillConfig",
"TableConfig.SkillLevelItemConfig",
"TableConfig.SkillTrigger",
"TableConfig.TouchHeadConfig",
"TableConfig.VehicleType",
"TableConfig.ViewModelState",
"UintList",
"UniGif",
"UniGif+GifTexture",
"UniGifExtension",
"UnityEngine.Android.Permission",
"UnityEngine.AndroidJavaClass",
"UnityEngine.AndroidJavaObject",
"UnityEngine.Animation",
"UnityEngine.AnimationCurve",
"UnityEngine.AnimationPlayMode",
"UnityEngine.Animator",
"UnityEngine.AnimatorStateInfo",
"UnityEngine.Application",
"UnityEngine.AssetBundle",
"UnityEngine.AsyncOperation",
"UnityEngine.AudioListener",
"UnityEngine.Behaviour",
"UnityEngine.BoxCollider",
"UnityEngine.Camera",
"UnityEngine.Camera+MonoOrStereoscopicEye",
"UnityEngine.CapsuleCollider",
"UnityEngine.Collider",
"UnityEngine.Color",
"UnityEngine.Color32",
"UnityEngine.ColorUtility",
"UnityEngine.Component",
"UnityEngine.Coroutine",
"UnityEngine.Debug",
"UnityEngine.Events.UnityAction",
"UnityEngine.FilterMode",
"UnityEngine.GameObject",
"UnityEngine.GL",
"UnityEngine.Graphics",
"UnityEngine.GUI",
"UnityEngine.GUILayout",
"UnityEngine.GUILayoutOption",
"UnityEngine.GUIStyle",
"UnityEngine.Input",
"UnityEngine.KeyCode",
"UnityEngine.Keyframe",
"UnityEngine.LayerMask",
"UnityEngine.Light",
"UnityEngine.Material",
"UnityEngine.Mathf",
"UnityEngine.Mesh",
"UnityEngine.MeshFilter",
"UnityEngine.MeshRenderer",
"UnityEngine.MonoBehaviour",
"UnityEngine.Networking.DownloadHandler",
"UnityEngine.Networking.DownloadHandlerBuffer",
"UnityEngine.Networking.DownloadHandlerFile",
"UnityEngine.Networking.DownloadHandlerScript",
"UnityEngine.Networking.UnityWebRequest",
"UnityEngine.Networking.UnityWebRequestAsyncOperation",
"UnityEngine.Networking.UploadHandler",
"UnityEngine.Networking.UploadHandlerRaw",
"UnityEngine.Object",
"UnityEngine.ParticleSystem",
"UnityEngine.ParticleSystem+MainModule",
"UnityEngine.Physics",
"UnityEngine.Playables.Playable",
"UnityEngine.Playables.PlayableDirector",
"UnityEngine.Playables.PlayableExtensions",
"UnityEngine.Playables.PlayableGraph",
"UnityEngine.PlayerPrefs",
"UnityEngine.Profiling.Profiler",
"UnityEngine.QualitySettings",
"UnityEngine.Quaternion",
"UnityEngine.Random",
"UnityEngine.Ray",
"UnityEngine.RaycastHit",
"UnityEngine.Rect",
"UnityEngine.RectTransform",
"UnityEngine.Renderer",
"UnityEngine.RenderTexture",
"UnityEngine.RenderTextureFormat",
"UnityEngine.RenderTextureReadWrite",
"UnityEngine.Resolution",
"UnityEngine.RuntimeAnimatorController",
"UnityEngine.SceneManagement.Scene",
"UnityEngine.SceneManagement.SceneManager",
"UnityEngine.Screen",
"UnityEngine.ScriptableObject",
"UnityEngine.Shader",
"UnityEngine.SkinnedMeshRenderer",
"UnityEngine.Space",
"UnityEngine.SphereCollider",
"UnityEngine.Sprite",
"UnityEngine.StackTraceUtility",
"UnityEngine.SystemInfo",
"UnityEngine.Terrain",
"UnityEngine.TextEditor",
"UnityEngine.Texture",
"UnityEngine.Texture2D",
"UnityEngine.TextureFormat",
"UnityEngine.TextureWrapMode",
"UnityEngine.Time",
"UnityEngine.Touch",
"UnityEngine.TouchScreenKeyboard",
"UnityEngine.TrailRenderer",
"UnityEngine.Transform",
"UnityEngine.UI.Text",
"UnityEngine.Vector2",
"UnityEngine.Vector3",
"UnityEngine.Vector4",
"UnityEngine.WaitForEndOfFrame",
"UnityEngine.WaitForSeconds",
"UnityEngine.WaitForSecondsRealtime",
"UnityEngine.WaitUntil",
"UnityEngine.WWW",
"UshortList",
"Utility",
"Vector3Extension",
"Vector3List",
"WaitViewLoad",
"Wup.Jce.JceHeadDataPool",
"Wup.Jce.JceInputStream",
"Wup.Jce.JceInputStream+HeadData",
"Wup.Jce.JceOutputStream",
"Wup.Utility.Util",
            };
        }
        // black list
        public static void OnGetNoUseList(out List<string> list)
        {
            list = new List<string>();
            /*
            list = new List<string>
            {      
                "HideInInspector",
                "ExecuteInEditMode",
                "AddComponentMenu",
                "ContextMenu",
                "RequireComponent",
                "DisallowMultipleComponent",
                "SerializeField",
                "AssemblyIsEditorAssembly",
                "Attribute", 
                "Types",
                "UnitySurrogateSelector",
                "TrackedReference",
                "TypeInferenceRules",
                "FFTWindow",
                "RPC",
                "Network",
                "MasterServer",
                "BitStream",
                "HostData",
                "ConnectionTesterStatus",
                "GUI",
                "EventType",
                "EventModifiers",
                "FontStyle",
                "TextAlignment",
                "TextEditor",
                "TextEditorDblClickSnapping",
                "TextGenerator",
                "TextClipping",
                "Gizmos",
                "ADBannerView",
                "ADInterstitialAd",            
                "Android",
                "Tizen",
                "jvalue",
                "iPhone",
                "iOS",
                "Windows",
                "CalendarIdentifier",
                "CalendarUnit",
                "CalendarUnit",
                "ClusterInput",
                "FullScreenMovieControlMode",
                "FullScreenMovieScalingMode",
                "Handheld",
                "LocalNotification",
                "NotificationServices",
                "RemoteNotificationType",      
                "RemoteNotification",
                "SamsungTV",
                "TextureCompressionQuality",
                "TouchScreenKeyboardType",
                "TouchScreenKeyboard",
                "UnityEngineInternal",
                "Terrain",                            
                "Tree",
                "SplatPrototype",
                "DetailPrototype",
                "DetailRenderMode",
                "MeshSubsetCombineUtility",
                "AOT",
                "Social",
                "Enumerator",       
                "SendMouseEvents",               
                "Cursor",
                "Flash",
                "ActionScript",
                "OnRequestRebuild",
                "Ping",
                "ShaderVariantCollection",
                "SimpleJson.Reflection",
                "CoroutineTween",
                "GraphicRebuildTracker",
                "Advertisements",
                "UnityEditor",
			    "WSA",
			    "EventProvider",
			    "Apple",
			    "ClusterInput",
                "CullingParameters",
                "CullResults",
                "ShadowSplitData",
                "DisposeSentinel",
                "ReflectionMethodsCache",
                "MovieTexture",
                "2D",
                "Cache",
                "CachedAssetBundle",
                "Caching",
                "Compute",
                "CharacterController",
                "ConstantForce",
                "ContactPoint",
                "ControllerColliderHit",
                "CrashReport",
                "Cubemap",
                "CullingGroup",
                "CustomRenderTexture",
                "Experimental",
                "Joint",
                "ForceMode",
                "Lightmap",
                "LightProbe",
                "Rendering",
                "Rigidbody",
                "CharacterInfo",
                "LOD",
                "Unsafe",
                "UnityM1Extension",
                "UnityM1Version",
				"ParticleSystemForceField",
                "UnityStats2"
            };
            */
        }
    }
}